declare var ENTITY: string;
declare var TAGNAME: string;
declare var ATTRIBUTE: string;
declare var OPENTAG: string;
declare var CLOSETAG: string;
declare var reHtmlTag: RegExp;
declare var ESCAPABLE: string;
declare var unescapeString: (s: any) => any;
declare var normalizeURI: (uri: any) => any;
declare var escapeXml: (s: string) => string;
export { unescapeString, normalizeURI, escapeXml, reHtmlTag, OPENTAG, CLOSETAG, ENTITY, ESCAPABLE, TAGNAME, ATTRIBUTE };
